### ISSUE TITLE
Request: Possible to change the KPS colours

### ISSUE THREAD

**Issue by Alipoodle** [yugecin/osukps#10]
For Mania 10 KPS isn't that fast, yet it displays as red (mainly because it's probably quiet fast for Standard player)
Would it be possible to set regions for where it is light blue, possibly another colour then red!
Or possibly fully customization for each range you want

**Comment by dnjstlr555** [comment]
That would be great! I will work on it.

**Comment by ExerciseBook** [comment]
你甚至可以学office的那个渐变调色板。

**Comment by yugecin** [comment]
added in [v6](https://github.com/yugecin/osukps/releases/latest)
