### ISSUE TITLE
0 Key does not work

### ISSUE THREAD

**Issue by korihax** [yugecin/osukps#20]
So i got the program and tried to start binding my keys for Stepmania but i only use numbers and not letters on my keyboard. 

Due to this i had to go in my .ini file to edit the keys manually and putting the actual numbers does not work so i had to use keycodes.

After many tries of this i got my 1, 2 and 9 keys to work but the 0 key does not work no matter what i change it to. Even the keycode (#47) does not work. So now i cannot use osukps on my live streams cause i cant get accurate results. 

Please fix this so i can use your program.

**Comment by yugecin** [comment]
Try code 48, 47 is the HELP key
(I've also added these in [the wiki](https://github.com/yugecin/osukps/wiki/virtual-key-codes), but it should be better handled in the program, will try to make a solution, apologies for the inconvenience)

**Comment by korihax** [comment]
48 was the right one thank you. It seems the website i got the information from must have been wrong. Apologizes.
