### ISSUE TITLE
keybinds only working half

### ISSUE THREAD

**Issue by gL1TcHeD0uT** [yugecin/osukps#25]
ive bound 4 buttons to d f j k and when i press them all, only j and k register

**Comment by yugecin** [comment]
When you play osu/stepmania/whatever you use this for, does that game register all 4 at the same time?
If not, then it's probably your keyboard ghosting.
If yes, then it's very strange and I don't know why :)

**Comment by boonsboos** [comment]
same person but different account since the old one got terminated for some reason.

i tried changing my keybinds again and suddenly it worked, weird bug but its resolved now

**Comment by yugecin** [comment]
ok good to hear :)
