### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by AshCubing** [yugecin/osukps#37]
When i try to save a setup, it never lets me load it/doesnt save.

**Comment by Kristianbek** [comment]
same for me

**Comment by GoldenLmao** [comment]
There is a easy fix to that if you haven't done it already it's placing the osupks application into a empty folder (can be any) then it should save properly.

**Comment by yugecin** [comment]
yes, as long as it's placed or you're running from a directory you have write access to, it should work.
