### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by mrgalaxyhasavirus** [yugecin/osukps#40]
it says it has virus in it, im confused

**Comment by yugecin** [comment]
I suppose antivirus programs can mark it as keylogger or something similar, as it handles with global keystates (https://github.com/yugecin/osukps/blob/180218/osukps/DefKeyHandler.cs#L7), but that's a very big assumption of the AV and a false positive. This program is only checking for keys that you have configured, and it's not collecting nor storing nor sending the keystrokes you do.

If you downloaded the exe from this repository itself (https://github.com/yugecin/osukps/releases/), it is clean.
