### ISSUE TITLE
Keys Bug +Arrow Key Support

### ISSUE THREAD

**Issue by marlnunz** [yugecin/osukps#41]
So One Day I Install It And Ye And I Put Thee Keybind And Yea And Then i press the a and isnt work But if i press CapsLock It Says The CapsLock Is The A keybind And I Try It With The Arrow Keys And isnt work but if i write right isnt work too so Can U add Arrow Key Support And Key Fix

**Comment by cheeselma** [comment]
just press the key you want while the key selection, but dont do the text thing. Alr? If it works, say thanks.

Posted by: Cheeselma

😃
