### ISSUE TITLE
virus total says that this has 3 viruses, should i trust virus total or the creator of this?

### ISSUE THREAD

**Issue by cheeselma** [yugecin/osukps#48]
just tell me lol

its not an issue, i just want to know if this is an virus

this is an proof

![image](https://user-images.githubusercontent.com/86810750/137232089-229dc5c8-b74a-46a9-bb16-6d0c2b35d862.png)

**Comment by yugecin** [comment]
not a virus

> I suppose antivirus programs can mark it as keylogger or something similar, as it handles with global keystates (https://github.com/yugecin/osukps/blob/180218/osukps/DefKeyHandler.cs#L7), but that's a very big assumption of the AV and a false positive. This program is only checking for keys that you have configured, and it's not collecting nor storing nor sending the keystrokes you do.
>
> If you downloaded the exe from this repository itself (https://github.com/yugecin/osukps/releases/), it is clean.

**Comment by cheeselma** [comment]
> not a virus
> 
> > I suppose antivirus programs can mark it as keylogger or something similar, as it handles with global keystates (https://github.com/yugecin/osukps/blob/180218/osukps/DefKeyHandler.cs#L7), but that's a very big assumption of the AV and a false positive. This program is only checking for keys that you have configured, and it's not collecting nor storing nor sending the keystrokes you do.
> > If you downloaded the exe from this repository itself (https://github.com/yugecin/osukps/releases/), it is clean.

dude, but idk if to trust to you or virustotal

**Comment by yugecin** [comment]
It's up to you, I can't do more than say what I just said. If you know a friend that can do C# you could get them to review the code and compile the program themselves.

**Comment by cheeselma** [comment]
well i will trust you since ur the creator lol
