### ISSUE TITLE
OSUKPS is a virus. 

### ISSUE THREAD

**Issue by mrgalaxyhasavirus** [yugecin/osukps#59]
![image](https://github.com/yugecin/osukps/assets/86635891/2bc150e3-23e0-461c-bd25-502fda11b1a5)

**Comment by yugecin** [comment]
what are the other two? or just share the link so I can look instead of a limited screenshot lol.
either way not gonna fix, false positive. If you don't trust it, don't run it. osukps captures keypresses globally so of course some might say it's a keylogger
